sudo: false
language: python
python:
  - "3.5"
install:
  - pip install erppeek coveralls
  - pip install -e .
  - pip install pep8
script:
  - coverage run ./tests/test.py
after_success:
  - coveralls
  - coverage report
  - pep8 .
  - pep8|wc -l